version: '1'
services:
  database:
    image: koenkk/docker-compose-exercise-database
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: movie123
    networks:
      - docker-compose-network-250

  webapp:
    image: koenkk/docker-compose-exercise-webapp
    container_name: mywebapp
    ports:
      - "8081:80"
    depends_on:
      - database
    networks:
      - docker-compose-network-250

networks:
  docker-compose-network-250:
    driver: bridge
